name: TruffleHog Scan

on: [pull_request]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install TruffleHog
        run: pip install trufflehog
      - name: Run TruffleHog
        id: trufflehog_scan
        run: trufflehog . --local --entropy=False --only-explicit
      # Run second time to compare the False positive outputs
      - name: Run TruffleHog
        id: trufflehog_scan_false
        run: trufflehog . --local
      - name: Report Findings and Fail on Secrets
        if: steps.trufflehog_scan.outcome == 'failure'
        run: |
          echo "Secrets have been found"
          exit 1